export const FIVE_DAY_DAILY_FORCAST_SUCCESS = 'FIVE_DAY_DAILY_FORCAST_SUCCESS';

export const CURRENT_WEATHER_BY_LOCATION_SUCCESS =
  'CURRENT_WEATHER_BY_LOCATION_SUCCESS';

export const LOCATION_AUTOCOMPLATE_SELECTED = 'LOCATION_AUTOCOMPLATE_SELECTED';
export const LOCATION_AUTOCOMPLATE_SUCCESS = 'LOCATION_AUTOCOMPLATE_SUCCESS';

export const TOGGLE_FAV = 'TOGGLE_FAV';

export const CHANGE_TEMPERATURE_UNIT = 'CHANGE_TEMPERATURE_UNIT';
export const ALLOW_NIGHT_MOOD = 'ALLOW_NIGHT_MOOD';

export const ERROR_HANDLER = 'ERROR_HANDLER';
export const HIDE_MODAL_ERROR = 'HIDE_MODAL_ERROR';
